version: '2'
services:
    vinyles-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/Vinyles/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Vinyles
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
